---
title: "ST2195 Coursework Project R Question 3"
author: "Jessica Lawrence Gunawan - 210421794"
date: "2023-01-02"
output: html_document
---

# ST2195 Coursework

## Question 3 : How does the number of people flying between different locations change over time?

```{r}
# Set working directory

setwd("~/Desktop/ST2195 Coursework Project")
```

```{r}
# Import and load necessary libraries

library(dplyr)
library(tidyverse)
library(ggplot2)
library(reshape2)
```

```{r}
# Load the datasets

flight2005 <- read.csv("2005.csv", header = TRUE)
flight2006 <- read.csv("2006.csv", header = TRUE)

airports <- read.csv("airports.csv", header = TRUE)
carriers <- read.csv("carriers.csv", header = TRUE)
plane_data <- read.csv("plane-data.csv", header = TRUE)
```

```{r}
# Row binding the flights data in 2005 and 2006

flights <- rbind(flight2005, flight2006)
```

```{r}
# Drop rows with missing values

flights <- flights %>%
  drop_na(DepTime, ArrTime, DepDelay, ArrDelay)
```

```{r}
# Re-check for any missing values

colSums(is.na(flights))
```

```{r}
# Creating a new column that defines the route of flights

flights <- flights %>% 
  mutate(route = paste(Origin, Dest, sep = "-"))

head(flights)
```

### Overview

```{r}
# Querying necessary data to analyse the total number of flights for each month in 2005

flight_count_2005 <- flights[flights$Year == 2005, ] %>%
  group_by(Year, Month) %>%
  summarise("Total Flights" = n())
                   
flight_count_2005
```

```{r}
# Querying necessary data to analyse the total number of flights for each month in 2006

flight_count_2006 <- flights[flights$Year == 2006, ] %>%
  group_by(Year, Month) %>%
  summarise("Total Flights" = n())
                   
flight_count_2006
```

```{r}
# Create a plot to see the number of people flying between different locations change over months in 2005 and 2006

months <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'June', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')

ggplot() +
  geom_line(data = flight_count_2005, aes(x = Month, y = `Total Flights`, color = '2005'), linewidth = 1) +
  geom_point(data = flight_count_2005, aes(x = Month, y = `Total Flights`, shape = '2005', color = '2005'), size = 3) +
  geom_line(data = flight_count_2006, aes(x = Month, y = `Total Flights`, color = '2006'), linetype = "dashed", linewidth = 1) +
  geom_point(data = flight_count_2006, aes(x = Month, y = `Total Flights`, shape = '2006', color = '2006'), size = 3) +
  scale_x_continuous(breaks = 1:12, labels = months) +
  scale_linetype_manual(name = "Year", values = c("2005" = "solid", "2006" = "dashed")) +
  scale_shape_manual(name = "Year", values = c("2005" = 16, "2006" = 16)) +
  scale_color_manual(name = "Year", values = c('2005' = 'red', '2006' = 'black')) +
  labs(x = "Month", y = "Total Flights", title = "Total Flights per Month in 2005-2006") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```

### Analysis by Month

```{r}
# Calculate the total number of flights for each route

route_count <- flights %>%
  group_by(route) %>%
  summarise("Total Flights" = n()) %>%
  rename(Route = route)

route_count
```

```{r}
# Sort route_count in descending order based on the total number of flights
route_count_sorted <- route_count %>% 
  arrange(desc(`Total Flights`))

# Select the top 5 routes with the highest number of total flights
top_routes <- head(route_count_sorted, 5)
top_routes
```

```{r}
# LAX-SAN

lax_san_month <- flights[flights$route == "LAX-SAN", ] %>%
  group_by(route, Month) %>%
  summarize("Total Flights" = n()) %>% 
  rename(Route = route)

lax_san_month
```

```{r}
# SAN-LAX

san_lax_month <- flights[flights$route == "SAN-LAX", ] %>%
  group_by(route, Month) %>%
  summarize("Total Flights" = n()) %>% 
  rename(Route = route)

san_lax_month
```

```{r}
# LAX-LAS

lax_las_month <- flights[flights$route == "LAX-LAS", ] %>%
  group_by(route, Month) %>%
  summarize("Total Flights" = n()) %>% 
  rename(Route = route)

lax_las_month
```

```{r}
# LAS-LAX

las_lax_month <- flights[flights$route == "LAS-LAX", ] %>%
  group_by(route, Month) %>%
  summarize("Total Flights" = n()) %>% 
  rename(Route = route)

las_lax_month
```

```{r}
# BOS-LGA

bos_lga_month <- flights[flights$route == "BOS-LGA", ] %>%
  group_by(route, Month) %>%
  summarize("Total Flights" = n()) %>% 
  rename(Route = route)

bos_lga_month
```

```{r}
# Create a plot to analyze the change in the number of people flying between different locations over months

ggplot() +
  geom_line(data = lax_san_month, aes(x = Month, y = `Total Flights`, color = 'LAX-SAN'), size = 1) +
  geom_point(data = lax_san_month, aes(x = Month, y = `Total Flights`, shape = 'LAX-SAN', color = 'LAX-SAN'), size = 3) +
  geom_line(data = san_lax_month, aes(x = Month, y = `Total Flights`, color = 'SAN-LAX'), size = 1) +
  geom_point(data = san_lax_month, aes(x = Month, y = `Total Flights`, shape = 'SAN-LAX', color = 'SAN-LAX'), size = 3) +
  geom_line(data = lax_las_month, aes(x = Month, y = `Total Flights`, color = 'LAX-LAS'), size = 1) +
  geom_point(data = lax_las_month, aes(x = Month, y = `Total Flights`, shape = 'LAX-LAS', color = 'LAX-LAS'), size = 3) +
  geom_line(data = las_lax_month, aes(x = Month, y = `Total Flights`, color = 'LAS-LAX'), size = 1) +
  geom_point(data = las_lax_month, aes(x = Month, y = `Total Flights`, shape = 'LAS-LAX', color = 'LAS-LAX'), size = 3) +
  geom_line(data = bos_lga_month, aes(x = Month, y = `Total Flights`, color = 'BOS-LGA'), size = 1) +
  geom_point(data = bos_lga_month, aes(x = Month, y = `Total Flights`, shape = 'BOS-LGA', color = 'BOS-LGA'), size = 3) +
  scale_x_continuous(breaks = 1:12, labels = c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'June', 'July', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')) +
  scale_color_manual(name = "Route", values = c('LAX-SAN' = 'red', 'SAN-LAX' = 'green', 'LAX-LAS' = 'gray', 'LAS-LAX' = 'blue', 'BOS-LGA' = 'orange')) +
  scale_shape_manual(name = "Route", values = c('LAX-SAN' = 16, 'SAN-LAX' = 16, 'LAX-LAS' = 16, 'LAS-LAX' = 16, 'BOS-LGA' = 16)) +
  labs(x = "Month", y = "Total Flights", title = "Top 5 Routes With Highest Number in Total Flights Over Months") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```

### Analysis by Year

```{r}
# Querying necessary data to analyse the total number of flights for each route in 2005

route_2005 <- flights[flights$Year == 2005,] %>%
  group_by(Year, route) %>%
  summarise("Total Flights" = n()) %>%
  rename(Route = route)

route_2005
```

```{r}
# Querying necessary data to analyse the total number of flights for each route in 2006

route_2006 <- flights[flights$Year == 2006,] %>%
  group_by(Year, route) %>%
  summarise("Total Flights" = n()) %>%
  rename(Route = route)

route_2006
```

```{r}
route_merged <- route_2005 %>% 
  inner_join(route_2006, by = "Route")

route_merged <- route_merged %>% 
  rename("Year 2005" = "Year.x", "Year 2006" = "Year.y", "Total Flights 2005" = "Total Flights.x", "Total Flights 2006" = "Total Flights.y")

route_merged <- select(route_merged, `Route`, `Year 2005`, `Total Flights 2005`, `Year 2006`, `Total Flights 2006`)

route_merged
```

```{r}
route_merged$"Total Flights" <- route_merged$"Total Flights 2005" + route_merged$"Total Flights 2006"  # Calculate the total number of flights in both years

route_merged$Difference <- route_merged$"Total Flights 2006" - route_merged$"Total Flights 2005"  # Calculate the difference in the total number of flights of 2005 and 2006 

route_merged$"% Change" <- route_merged$Difference/route_merged$"Total Flights 2005"*100  # Calculate the percentage difference

route_merged
```

```{r}
# Sort route_count in descending order based on the total number of flights
route_merged_sorted <- route_merged %>% 
  arrange(desc(`Total Flights`))

# Select the top 5 routes with the highest number of total flights
top_5_routes <- head(route_merged_sorted, 5)
top_5_routes
```

```{r}
# Melt the data

top_5_routes_melt <- select(top_5_routes, `Route`, `Total Flights 2005`, `Total Flights 2006`) %>% 
  rename(`2005` = `Total Flights 2005`, `2006` = `Total Flights 2006`)
top_5_routes_melt <- melt(top_5_routes_melt)
names(top_5_routes_melt) <- c("Route", "Year", "Total Flights")
top_5_routes_melt
```

```{r}
# Create a plot to analyse the change in the total number of flights in 2005 and 2006 for the 5 routes

ggplot(top_5_routes_melt, aes(x = Route, y = `Total Flights`, fill = Year)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = `Total Flights`), position = position_dodge(width = 1), vjust = -0.5, hjust = 0.5, size = 3) +
  scale_fill_manual(values=c("cyan", "gray"), name="Year", labels=c("2005", "2006")) +
  ylim(0, 20000) +
  labs(title = "Top 5 Routes With Highest Number in Total Flights Over The Years") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# Create a plot to analyse the change in the total number of flights in 2005 and 2006 for the 5 routes using % change

ggplot() +
  geom_line(data = top_5_routes, aes(x = Route, y = `% Change`), group = group_vars, size = 1) +
  geom_point(data = top_5_routes, aes(x = Route, y = `% Change`), size = 3, shape = 16) + 
  labs(title = " % Change of The Top 5 Routes With Highest Number in Total Flights Over The Years") +
  annotate("text", x=top_5_routes$Route, y=top_5_routes$`% Change`, label=paste0(round(top_5_routes$`% Change`, 1), "%"), vjust=1.5, color="black") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# Create a plot to analyse the change in the total number of flights in 2005 and 2006 for the 5 routes using % change

ggplot(top_5_routes, aes(x = Route, y = `% Change`)) + 
  geom_line(group = 1, linewidth = 1) +
  geom_point(data = top_5_routes, aes(x = Route, y = `% Change`), size = 3, shape = 16) + 
  ylim(-10, 10) +
  labs(x = "Route", y = "% Change", title = "The % Change of Total Number of Flights in 2005 and 2006 for The Top 5 Routes") +
  annotate("text", x=top_5_routes$Route, y=top_5_routes$`% Change`, label=paste0(round(top_5_routes$`% Change`, 1), "%"), vjust=1.5, color="black") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
```
