---
title: "ST2195 Coursework Project R Question 5"
author: "Jessica Lawrence Gunawan - 210421794"
date: "2023-01-02"
output: html_document
---

# ST2195 Coursework

## Question 5 : Use the available variables to construct a model that predicts delays.

```{r}
# Set working directory

setwd("~/Desktop/ST2195 Coursework Project")
```

```{r}
# Import and load necessary libraries

library(dplyr)
library(tidyverse)
library(ggplot2)
library(skimr)
library(mlr3)
library(mlr3pipelines)
library(mlr3learners)
library(paradox)
library(mlr3tuning)
library(glmnet)
library(ranger)
```

```{r}
# Load the datasets

flight2005 <- read.csv("2005.csv", header = TRUE)
flight2006 <- read.csv("2006.csv", header = TRUE)

airports <- read.csv("airports.csv", header = TRUE)
carriers <- read.csv("carriers.csv", header = TRUE)
plane_data <- read.csv("plane-data.csv", header = TRUE)
```

```{r}
# Row binding the flights data in 2005 and 2006

flights <- rbind(flight2005, flight2006)
```

```{r}
# Drop rows with missing values

flights <- flights %>%
  drop_na(DepTime, ArrTime, DepDelay, ArrDelay)
```

```{r}
# Re-check for any missing values

colSums(is.na(flights))
```

```{r}
# Skimming the dataset

skim(flights)
```

### Construct a Model That Predicts Arrival Delay

```{r}
# Querying numerical variables that are required for building the future prediction (i.e. Subsetting the dataset by its features & the target)

flights_variable <- flights %>% 
  select(CRSDepTime, CRSArrTime, CRSElapsedTime, Year, Month, DayofMonth, DayOfWeek, ArrDelay)
```

```{r}
# Set up a task and specifying the target variable

task <- TaskRegr$new(id = "flights_variable", backend = flights_variable, target = "ArrDelay")
```

```{r}
# Set MSE as the measure

measure <- msr('regr.mse')
```

```{r}
# Split Data Into Train and Test Set

set.seed(1)
train_set <- sample(task$nrow, 0.7 * task$nrow) 
test_set <- setdiff(seq_len(task$nrow), train_set)
```

### Linear Regression Model

```{r}
learner_lm <- lrn('regr.lm')
gr_lm <- po('scale') %>>%
  po('imputemean') %>>%
  po(learner_lm)  
glrn_lm <- GraphLearner$new(gr_lm)
```

```{r}
glrn_lm$train(task, row_ids = train_set)
```

```{r}
# The performance score of the linear regression model on the training set

mse_train_lm <- glrn_lm$predict(task, row_ids = train_set)$score()
mse_train_lm
```

```{r}
# The performance score of the linear regression model on the test set

mse_test_lm <- glrn_lm$predict(task, row_ids = test_set)$score() 
mse_test_lm
```

### Ridge Regression Model

```{r}
learner_ridge <- lrn('regr.glmnet') 
learner_ridge$param_set$values <- list(alpha = 0)
gr_ridge <- po('scale') %>>%
  po('imputemean') %>>%
  po(learner_ridge)
glrn_ridge <- GraphLearner$new(gr_ridge)
```

```{r}
# Set up tuning environment

tune_lambda <- ParamSet$new (list(
 ParamDbl$new('regr.glmnet.lambda', lower = 0.001, upper = 1)
))
tuner<-tnr('grid_search')
terminator <- trm('evals', n_evals = 5)
```

```{r}
at_ridge <- AutoTuner$new(
  learner = glrn_ridge,
  resampling = rsmp('cv', folds = 3),
  measure = measure,
  search_space = tune_lambda,
  terminator = terminator,
  tuner = tuner
)
```

```{r}
at_ridge$train(task, row_ids = train_set)
```

```{r}
# The performance score of the ridge regression model on the training set

mse_train_ridge <- at_ridge$predict(task, row_ids = train_set)$score()
mse_train_ridge
```

```{r}
# The performance score of the ridge regression model on the test set

mse_test_ridge <- at_ridge$predict(task, row_ids = test_set)$score() 
mse_test_ridge
```

### Lasso Regression Model

```{r}
learner_lasso <- lrn('regr.glmnet') 
learner_lasso$param_set$values <- list(alpha = 1)
gr_lasso <- po('scale') %>>%
  po('imputemean') %>>%
  po(learner_lasso)
glrn_lasso <- GraphLearner$new(gr_lasso)
```

```{r}
# Set up tuning environment

tune_lambda <- ParamSet$new (list(
 ParamDbl$new('regr.glmnet.lambda', lower = 0.001, upper = 1)
))
tuner<-tnr('grid_search')
terminator <- trm('evals', n_evals = 5)
```

```{r}
at_lasso <- AutoTuner$new(
  learner = glrn_lasso,
  resampling = rsmp('cv', folds = 3),
  measure = measure,
  search_space = tune_lambda,
  terminator = terminator,
  tuner = tuner
)
```

```{r}
at_lasso$train(task, row_ids = train_set)
```

```{r}
# The performance score of the lasso regression model on the training set

mse_train_lasso <- at_lasso$predict(task, row_ids = train_set)$score()
mse_train_lasso
```

```{r}
# The performance score of the ridge regression model on the test set

mse_test_lasso <- at_lasso$predict(task, row_ids = test_set)$score() 
mse_test_lasso
```

### Random Forest Model (using sample)

```{r}
# Randomnly select 100,000 rows from the flights dataframe

set.seed(1)
sample_flights <- flights[sample(nrow(flights), 100000, replace = FALSE), ]
```

```{r}
# Querying numerical variables that are required for building the future prediction (i.e. Subsetting the dataset by its features & the target)

sample_flights_variable <- sample_flights %>% 
  select(CRSDepTime, CRSArrTime, DepDelay, LateAircraftDelay, CarrierDelay, NASDelay, WeatherDelay, SecurityDelay, ArrDelay)
```

```{r}
# Set up a task and specifying the target variable

task <- TaskRegr$new(id='sample_flights_variable', backend=sample_flights_variable, target='ArrDelay')
```

```{r}
# Split Data Into Train and Test Set

set.seed(1)
train_set <- sample(task$nrow, 0.7 * task$nrow) 
test_set <- setdiff(seq_len(task$nrow), train_set)
```

```{r}
learner_rf <- lrn('regr.ranger') 
learner_rf$param_set$values <- list(min.node.size = 4)
gr_rf <- po('scale') %>>%
  po('imputemean') %>>%
  po(learner_rf)
glrn_rf <- GraphLearner$new(gr_rf)
```

```{r}
tune_ntrees <- ParamSet$new (list(
 ParamInt$new('regr.ranger.num.trees', lower = 100, upper = 600)
))
```

```{r}
at_rf <- AutoTuner$new(
  learner = glrn_rf,
  resampling = rsmp('cv', folds = 3),
  measure = measure,
  search_space = tune_ntrees,
  terminator = terminator,
  tuner = tuner
)
```

```{r}
at_rf$train(task, row_ids = train_set)
```

```{r}
# The performance score of the random forest model on the training set

mse_train_rf <- at_rf$predict(task, row_ids = train_set)$score()
mse_train_rf
```

```{r}
# The performance score of the random forest model on the test set

mse_test_rf <- at_rf$predict(task, row_ids = test_set)$score() 
mse_test_rf
```

### Comparing The Performance Score between Linear Regression, Ridge Regression, and Random Forest

```{r}
model_compare <- data.frame(
" " = c("MSE on train data", "MSE on test data"),
"Linear Regression" = c(mse_train_lm, mse_test_lm),
"Ridge Regression" = c(mse_train_ridge, mse_test_ridge),
"Lasso Regression" = c(mse_train_lasso, mse_test_lasso),
"Random Forest" = c(mse_train_rf, mse_test_rf)
)

model_compare
```
