---
title: "ST2195 Coursework Project R Question 1"
author: "Jessica Lawrence Gunawan - 210421794"
date: "2023-01-02"
output: html_document
---

# ST2195 Coursework

## Question 1 : When is the best time of day, day of the week, and time of year to fly to minimise delays?

```{r}
# Set working directory

setwd("~/Desktop/ST2195 Coursework Project")
```

```{r}
# Import and load necessary libraries

library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r}
# Load the datasets

flight2005 <- read.csv("2005.csv", header = TRUE)
flight2006 <- read.csv("2006.csv", header = TRUE)

airports <- read.csv("airports.csv", header = TRUE)
carriers <- read.csv("carriers.csv", header = TRUE)
plane_data <- read.csv("plane-data.csv", header = TRUE)
```

```{r}
# Row binding the flights data in 2005 and 2006

flights <- rbind(flight2005, flight2006)
```

```{r}
# Look at the summary of the flights dataset

str(flights)
```

```{r}
# Check for any missing values

colSums(is.na(flights))
```

```{r}
# Drop rows with missing values

flights <- flights %>%
  drop_na(DepTime, ArrTime, DepDelay, ArrDelay)
```

```{r}
# Re-check for any missing values

colSums(is.na(flights))
```

### Best Time of Day

```{r}
# Group the CRSDepTime by 2 hours interval 

flights <- flights %>%
  mutate(deptime_interval = case_when(CRSDepTime >= 000 & CRSDepTime < 200 ~ "00.00 - 01.59",
                                        CRSDepTime >= 200 & CRSDepTime < 400 ~ "02.00 - 03.59",
                                        CRSDepTime >= 400 & CRSDepTime < 600 ~ "04.00 - 05.59",
                                        CRSDepTime >= 600 & CRSDepTime < 800 ~ "06.00 - 07.59",
                                        CRSDepTime >= 800 & CRSDepTime < 1000 ~ "08.00 - 09.59",
                                        CRSDepTime >= 1000 & CRSDepTime < 1200 ~ "10.00 - 11.59",
                                        CRSDepTime >= 1200 & CRSDepTime < 1400 ~ "12.00 - 13.59",
                                        CRSDepTime >= 1400 & CRSDepTime < 1600 ~ "14.00 - 15.59",
                                        CRSDepTime >= 1600 & CRSDepTime < 1800 ~ "16.00 - 17.59",
                                        CRSDepTime >= 1800 & CRSDepTime < 2000 ~ "18.00 - 19.59",
                                        CRSDepTime >= 2000 & CRSDepTime < 2200 ~ "20.00 - 21.59",
                                        CRSDepTime >= 2200 & CRSDepTime < 2400 ~ "22.00 - 23.59",
))
```

```{r}
# Analyzing the percentage number of delayed flights per 2 hours time interval in a day

best_time_of_day_count <- flights %>%
  group_by(deptime_interval) %>%
  summarise(delayed_flights = sum(ArrDelay > 0),
            total_flights = n()) %>% 
  mutate(`% of delayed flights` = (delayed_flights / total_flights) * 100)

best_time_of_day_count
```

```{r}
# Analyzing the average of delay per deptime_interval

best_time_of_day_mean <- flights %>%
  filter(ArrDelay > 0) %>%
  group_by(deptime_interval) %>%
  summarise(`average arrdelay` = mean(ArrDelay))

best_time_of_day_mean
```

```{r}
# Combine 'best_time_of_day_count' and 'best_time_of_day_mean'

best_time_of_day <- merge(best_time_of_day_count, best_time_of_day_mean, by="deptime_interval")
names(best_time_of_day) <- c('Time Interval', 'Total Delayed Flights', 'Total Flights', '% of Delayed Flights', 'Average Arrival Delay')

best_time_of_day
```

```{r}
# Create two plots for analyzing the best time of day

labels <- c('12 - 1.59 AM', '2 - 3.59 AM', '4 - 5.59 AM', '6 - 7.59 AM', '8 - 9.59 AM', '10 - 11.59 AM', '12 - 1.59 PM', '2 - 3.59 PM', '4 - 5.59 PM', '6 - 7.59 PM', '8 - 9.59 PM', '10 - 11.59 PM')

# Create plot for percentage of delayed flights
ggplot(best_time_of_day, aes(x = `Time Interval`, y = `% of Delayed Flights`, fill = `% of Delayed Flights`)) + 
  geom_col(fill = "#F2BAC9", width = 0.5)  +
  scale_x_discrete(labels = labels) +
  labs(x = "Departure Time Interval", y = "% of Delayed Flights",
       title = "Percentage of Delayed Flights in 2005-2006",
       subtitle = "(per 2 hours)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) 
```

```{r}
# Create plot for average delay
ggplot(best_time_of_day, aes(x = `Time Interval`, y = `Average Arrival Delay`, fill = `Average Arrival Delay`)) + 
  geom_col(fill = "#8ADBEB", width = 0.5) +
  scale_x_discrete(labels = labels) +
  labs(x = "Departure Time Interval", y = "Average Arrival Delay (minutes)",
       title = "Average Delay in 2005-2006",
       subtitle = "(per 2 hours)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))
```

### Best Day of The Week

```{r}
# Analyzing the percentage of total delayed flights per day

best_day_of_week_count <- flights %>% 
  group_by(DayOfWeek) %>% 
  summarise(delayed_flights = sum(ArrDelay > 0),
            total_flights = n()) %>% 
  mutate('% of delayed flights' = (delayed_flights / total_flights) * 100)

best_day_of_week_count
```

```{r}
# Analyzing the average of delay per day

best_day_of_week_mean <- flights %>%
  filter(ArrDelay > 0) %>%
  group_by(DayOfWeek) %>%
  summarise(`average arrdelay` = mean(ArrDelay))

best_day_of_week_mean
```

```{r}
# Combine 'best_day_of_week_count' and 'best_day_of_week_mean'

best_day_of_week <- merge(best_day_of_week_count, best_day_of_week_mean, by="DayOfWeek")
names(best_day_of_week) <- c('Day of Week', 'Total Delayed Flights', 'Total Flights', '% of Delayed Flights', 'Average Arrival Delay')

best_day_of_week
```

```{r}
# Create two plots for analyzing the best day of week

labels <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')

# Create a plot for percentage of delayed flights
ggplot(best_day_of_week, aes(x = `Day of Week`, y = `% of Delayed Flights`, fill = `% of Delayed Flights`)) + 
  geom_col(fill = "#FFE199", width = 0.5)  +
  scale_x_continuous(breaks = 1:7, labels = labels) +
  labs(x = "Day of Week", y = "% of Delayed Flights",
       title = "Percentage of Delayed Flights in 2005-2006",
       subtitle = "(per day)") +
  theme_classic() +
  theme(axis.text.x = element_text(vjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) 
```

```{r}
# Create a plot for average delay

ggplot(best_day_of_week, aes(x = `Day of Week`, y = `Average Arrival Delay`, fill = `Average Arrival Delay`)) + 
  geom_col(fill = "#67F5D8", width = 0.5)  +
  scale_x_continuous(breaks = 1:7, labels = labels) +
  labs(x = "Day of Week", y = "Average Arrival Delay (minutes)",
       title = "Average Delay in 2005 & 2006",
       subtitle = "(per day)") +
  theme_classic() +
  theme(axis.text.x = element_text(vjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) 
```

### Best Time of Year

```{r}
# Analyzing the percentage of total delayed flights per month

best_time_of_year_count <- flights %>% 
  group_by(Month) %>% 
  summarise(delayed_flights = sum(ArrDelay > 0),
            total_flights = n()) %>% 
  mutate('% of delayed flights' = (delayed_flights / total_flights) * 100)

best_time_of_year_count
```

```{r}
# Analyzing the average of delay per month

best_time_of_year_mean <- flights %>%
  filter(ArrDelay > 0) %>%
  group_by(Month) %>%
  summarise(`average arrdelay` = mean(ArrDelay))

best_time_of_year_mean
```

```{r}
# Combine 'best_day_of_week_count' and 'best_day_of_week_mean'

best_time_of_year <- merge(best_time_of_year_count, best_time_of_year_mean, by="Month")
names(best_time_of_year) <- c('Month', 'Total Delayed Flights', 'Total Flights', '% of Delayed Flights', 'Average Arrival Delay')

best_time_of_year
```

```{r}
# Create two plots for analyzing the best time of year

labels <- c('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')

# Create a plot for percentage of delayed flights
ggplot(best_time_of_year, aes(x = `Month`, y = `% of Delayed Flights`, fill = `% of Delayed Flights`)) +
  geom_col(fill = "#FFBCAD", width = 0.5)  +
  scale_x_continuous(breaks = 1:12, labels = labels) +
  labs(x = "Month", y = "% of Delayed Flights",
       title = "Percentage of Delayed Flights in 2005-2006",
       subtitle = "(per month)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) 
```

```{r}
# Create a plot for average delay

ggplot(best_time_of_year, aes(x = `Month`, y = `Average Arrival Delay`, fill = `Average Arrival Delay`)) +
  geom_col(fill = "#AFC3FA", width = 0.5)  +
  scale_x_continuous(breaks = 1:12, labels = labels) +
  labs(x = "Month", y = "Average Arrival Delay (minutes)",
       title = "Average Arrival Delay in 2005-2006",
       subtitle = "(per month)") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) 
```
